### PR TITLE
Reverse complement function added to ersatz

### PR DESCRIPTION
**Pull request by Al-Murphy**
Reverse Complement of DNA sequences is such a common approach to training/testing genomic deep learning models so I have added functionality to `ersatz`.

### CODE REVIEW

**Comment by jmschrei** [comment]
Thanks! Conceptually, this looks good, but I have two thoughts: (1) maybe it'd be best to pass in the mapping rather than an alphabet with an assumed mapping? That would allow the function to work when people have modified bases or whatever. (2) Currently, the tensor input assumes a batch of sequences but the string input assumes a single one. Maybe it'd be best to be consistent and have this function only work on a single sequence, just like the one-hot encode function?

**Comment by Al-Murphy** [comment]
Updated now! Implemented point 1 and 2 but just on 1 - I agree having the mapping as an input is a good idea to allow for custom mappings but I still think we need to have an alphabet so we can infer the order. See what you think of the update and let me know if I'm missing something. the `allow_N` is also now redundant as the choice is captured in the mapping. Moreover, just to note, this approach which now has less assumptions does take notably longer to run (and uses more memory) but perhaps this is still okay - 620 μs vs 27.9 μs on a sequence the 1 million base-pairs?:

```
from tangermeme.ersatz import random_one_hot
import torch
import timeit

seq = random_one_hot((1,4, 1_000_000), random_state=0)[0]

complement_map = {"A": "T",
                  "T": "A",
                  "C": "G",
                  "G": "C",
                  "N": "N"}
alphabet=['A', 'C', 'G', 'T']


print("-----------------------------")

def rc(seq):
    # Create a tensor to hold the reverse complement
    rev_comp = torch.zeros_like(seq)

    # Fill in the reverse complement tensor
    for i, base in enumerate(alphabet):
        comp_base = complement_map[base]
        comp_index = alphabet.index(comp_base)
        rev_comp[comp_index] = torch.flip(seq[i], dims=[0])
    return rev_comp

%timeit -n 10000 rc(seq)

print("-----------------------------")


%timeit -n 10000 torch.flip(seq,dims=[0,1])

print(torch.equal(rc(seq),torch.flip(seq,dims=[0,1])))
```

Output:

```
-----------------------------
620 μs ± 21.5 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
-----------------------------
27.9 μs ± 936 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

True
```

**Comment by jmschrei** [comment]
Sorry for the delay in getting to this. Had several back-to-back things come up and wanted to get this latest version out. I will take a look at this again soon.

**Comment by jmschrei** [comment]
I've incorporated this but refactored it a bit to be simpler and more consistent with the rest of the code-base. Thanks for the contribution!

**Pull request merged**
